schemaVersion: 2.1.0
metadata:
  name: devspaces-demo
components:
  - name: tooling-container
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 256M
      memoryLimit: 1536M
      cpuRequest: 100m
      cpuLimit: 1500m
commands:
  - id: 1-install-ansible-navigator
    exec:
      label: "1-install-ansible-navigator"
      component: tooling-container
      commandLine: python3 -m pip install ansible-navigator --user
  - id: 2-set-profile
    exec:
      label: "2-set-profile"
      component: tooling-container
      commandLine: echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.profile
  - id: 3-source-profile
    exec:
      label: "3-source-profile"
      component: tooling-container
      commandLine: source ~/.profile
  - id: 4-run-navigator
    exec:
      label: "4-run-navigator"
      component: tooling-container
      commandLine: ansible-navigator
  - id: 5-test
    exec:
      label: "test"
      component: tooling-container
      commandLine: touch /tmp/test
